### ISSUE TITLE
ScheduledTasks and C1 CMS 6.4

### ISSUE THREAD

**Issue by aeont** [burningice2866/CompositeC1Contrib#6]
Please update ScheduledTasks to work with C1 CMS 6.4. and latest dlls versions. 

After upgrade to C1 CMS 6.4. and clicking ScheduledTasks in console  - storage init error and exception.

**Initialization (same as with 6.2):**
`[assembly: OwinStartup(typeof(Startup))]
namespace BlackBox
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCompositeC1ContribScheduledTasks(f => f.JobStorage = new CompositeC1Storage());
            //Library.Account.Startup.ConfigureAuth(app);
        }
    }
}`

**Exception:**

`System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.InvalidOperationException: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.
at Hangfire.JobStorage.get_Current()
at CompositeC1Contrib.ScheduledTasks.C1Console.ElementProviders.ScheduledTasksElementProvider.d__10.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at Composite.Core.Linq.IEnumerableExtensions.Evaluate[T](IEnumerable`1 enumerable)
at Composite.C1Console.Elements.ElementFacade.GetChildren(ElementHandle elementHandle, SearchToken searchToken, Boolean performSecurityCheck, Boolean useForeign)
at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.GetChildren(String providerName, String serializedEntityToken, String piggybag, String serializedSearchToken)
at Composite.Services.TreeServices.GetElementsBySearchToken(ClientElement clientElement, String serializedSearchToken) in \Website\Composite\services\Tree\TreeServices.asmx:line 289
at Composite.Services.TreeServices.GetElements(ClientElement clientElement) in \Website\Composite\services\Tree\TreeServices.asmx:line 214
--- End of inner exception stack trace ---`

**Comment by aeont** [comment]
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.InvalidOperationException: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.
   at Hangfire.JobStorage.get_Current()
   at CompositeC1Contrib.ScheduledTasks.C1Console.ElementProviders.ScheduledTasksElementProvider.<GetChildren>d__10.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Composite.Core.Linq.IEnumerableExtensions.Evaluate[T](IEnumerable`1 enumerable)
   at Composite.C1Console.Elements.ElementFacade.GetChildren(ElementHandle elementHandle, SearchToken searchToken, Boolean performSecurityCheck, Boolean useForeign)
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.GetChildren(String providerName, String serializedEntityToken, String piggybag, String serializedSearchToken)
   at Composite.Services.TreeServices.GetElementsBySearchToken(ClientElement clientElement, String serializedSearchToken) in \Website\Composite\services\Tree\TreeServices.asmx:line 289
   at Composite.Services.TreeServices.GetElements(ClientElement clientElement) in \Website\Composite\services\Tree\TreeServices.asmx:line 214
   --- End of inner exception stack trace ---

**Comment by aeont** [comment]
> [assembly: OwinStartup(typeof(Startup))]
namespace BlackBox
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCompositeC1ContribScheduledTasks(f => f.JobStorage = new CompositeC1Storage());
            //Library.Account.Startup.ConfigureAuth(app);
        }
    }
}

**Comment by burningice2866** [comment]
@aeont can you try throwing an exception in your Owin Startup Handler to ensure that it's being called?

**Comment by aeont** [comment]
@burningice2866 Thank you! sorted out. My Resharper cleaned unused reference which is Microsoft.Owin.Host.SystemWeb.
